### PR TITLE
Fix some templates still using quarkiverse- prefix

### PR DESCRIPTION
**Pull request by rquinio1A**
Align with the new conventions, to avoid confusion.
It's sad github templates don't support variables :/

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Thank you!

>It's sad github templates don't support variables :/

Yeah, we'll end up using the `quarkus:create-extension` command eventually since it is more flexible than GitHub Templates.

**Comment by ia3andy** [comment]
Thanks @gastaldi it was already ok in the codestarts :)

**Comment by ia3andy** [comment]
Maybe we should switch to the command instead of the github template?

**Comment by gastaldi** [comment]
@ia3andy Yes, I think that's a good idea. I'll archive/deprecate the GitHub template when the create-extension command is available in a released Quarkus version

**Comment by ia3andy** [comment]
@gastaldi it is in 1.12.0.Final
```shell
$ mvn io.quarkus:quarkus-maven-plugin:create-extension -DgroupId=io.quarkiverse.myext -DextensionId=my-ext  

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.0.Final:create-extension (default-cli) @ standalone-pom ---

Detected layout type is 'quarkiverse' 
Generated runtime artifactId is 'quarkus-my-ext'


applying codestarts...
🔠 java
🧰 maven
🗃 quarkus-extension
🛠 git
🐒 devmode-test
🐒 extension-base
🐒 integration-test
🐒 quarkiverse
🐒 unit-test

-----------
👍 extension has been successfully generated in:
--> /Users/ia3andy/workspace/redhat/quarkus/code.quarkus.io/target/quarkus-my-ext
-----------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.362 s
[INFO] Finished at: 2021-03-11T14:44:47+01:00
[INFO] ------------------------------------------------------------------------

```

FYI `-DgroupId=io.quarkiverse.myext`  would be enough but you'd get `quarkus-myext` as extensionId

**Comment by gastaldi** [comment]
Nice, I am sold. I'll archive the repository and start using the command right now

**Pull request merged**
